### ISSUE TITLE
app-store 商品信息需编译到本地

### ISSUE THREAD

**Issue by chendelin1982** [Websoft9/plugin-appstore#35]
**What type of your feature request?**  

当前 appstore 是直接连接 contentful 中的主数据，后期需要考虑将数据编译到本地
可能可以解决此问题的框架：[Create React App](https://github.com/facebook/create-react-app)

**Comment by zhaojing1987** [comment]
在create-react-app中，没有第三插件能将contentful的数据拉取到本地进行预存储，目前的解决方案：
1、通过contentful CLI 工具将数据导出json文件
2、通过react的插件将json格式转换为GraphQL格式，例如：json-to-graphql-query
3、在react中使用GraphQL客户端对GraphQL文件进行查询，例如：[GraphQL-React](https://github.com/jaydenseric/graphql-react) 或者 [apollographql](https://www.apollographql.com/tutorials/fullstack-quickstart/10-managing-local-state)
