### ISSUE TITLE
can not list applications when select chinese language

### ISSUE THREAD

**Issue by qiaofeng1227** [Websoft9/plugin-appstore#49]
- [x] appstore set chinese on china server, whether use vpn or not use vpn 
- [x] appstore set english on china server, whether use vpn or not use vpn 
- [x] appstore set english on foreign server, whether use vpn or not use vpn 
- [x] appstore set chinese on foreign server, use vpn
- [ ] appstore set chinese on foreign server, not use vpn

**Comment by qiaofeng1227** [comment]
![image](https://github.com/Websoft9/plugin-appstore/assets/43192516/65218fd0-a7a4-45ba-8a28-caf0dcd916af)

**Comment by chendelin1982** [comment]
try bind apphub to Internet Port, then access api by InternetIP:port, that can test is don't depends on Nginx @zhaojing1987 @qiaofeng1227
