### ISSUE TITLE
add more links to appstore's app detail page

### ISSUE THREAD

**Issue by chendelin1982** [Websoft9/plugin-appstore#64]
**What type of your feature request?**  

![image](https://github.com/user-attachments/assets/f2daa5bb-7842-4d64-b856-6b04ed51e0b6)

- [x] add app's Github URL
- [x] add Categorization path for application
- [x] website, documentaion, github links separate display

**Comment by morning-tan** [comment]
![Uploading 20240806.jpg…]()

**Comment by morning-tan** [comment]
![image](https://github.com/user-attachments/assets/a21f1d0c-1aa2-438c-8fa1-5d19bd58a3a0)

**Comment by qiaofeng1227** [comment]
1. 产品logo链接 app官网
2. version只显示一行，使用tooltip，鼠标移动上去显示全部
3. github图标链接docker-library的app（e.g. https://github.com/Websoft9/docker-library/tree/main/apps/aitable）

**Comment by chendelin1982** [comment]
solved
